//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvalMaster()
        {
            this.EvalDetails = new HashSet<EvalDetail>();
        }
    
        public int EvalMasterId { get; set; }
        public string Remark { get; set; }
        public string EvalStateCode { get; set; }
        public Nullable<int> EvalPeriodId { get; set; }
        public Nullable<int> BeEvalEmployeeId { get; set; }
        public Nullable<int> EvalEmployeeId { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public Nullable<bool> IsForDepartment { get; set; }
        public string EvalResultCode { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string StrongPoint { get; set; }
        public string WeakPoint { get; set; }
        public string Target { get; set; }
        public string Learning { get; set; }
        public string LearnTime { get; set; }
        public string Condition { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvalDetail> EvalDetails { get; set; }
        public virtual EvalPeriod EvalPeriod { get; set; }
        public virtual EvalState EvalState { get; set; }
    }
}
