//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalResult
    {
        public string EvalResultCode { get; set; }
        public string EvalResultName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Idx { get; set; }
    }
}
